name: QA Python

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        default: '3.13'
        required: false
        type: string
      ruff_lint:
        description: Use Ruff for linting
        default: true
        required: false
        type: boolean
      ruff_format:
        description: Check formatting with Ruff
        default: true
        required: false
        type: boolean
      pyright:
        description: Use Pyright for type checking
        default: true
        required: false
        type: boolean

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "${{ inputs.PYTHON_VERSION }}"

      - name: Install dependencies
        run: uv sync --frozen --all-extras --dev

      - name: Ruff
        if: inputs.ruff_lint
        run: uv run ruff check
      
      - name: Ruff format check
        if: inputs.ruff_format
        run: uv run ruff format --check --diff
      
      - name: Pyright
        if: inputs.pyright
        run: uv run pyright